In [1]:
import numpy as np
import pandas as pd

In [2]:
# looping through pandas series

In [3]:
ser = pd.Series([np.arange(10)])
for i in ser:
    print(i)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# looping through pandas df

In [5]:
df = pd.DataFrame(np.arange(10).reshape(5,2),columns=['x1','x2'])
df

x1  x2
0   0   1
1   2   3
2   4   5
3   6   7
4   8   9

In [6]:
for i in df:
    print(i)

x1
x2


In [7]:
for i in np.arange(df.shape[0]):
    print(df.iloc[i])

x1    0
x2    1
Name: 0, dtype: int32
x1    2
x2    3
Name: 1, dtype: int32
x1    4
x2    5
Name: 2, dtype: int32
x1    6
x2    7
Name: 3, dtype: int32
x1    8
x2    9
Name: 4, dtype: int32


In [8]:
for i in np.arange(df.shape[1]):
    print(df.iloc[:,i])

0    0
1    2
2    4
3    6
4    8
Name: x1, dtype: int32
0    1
1    3
2    5
3    7
4    9
Name: x2, dtype: int32


In [9]:
df

x1  x2
0   0   1
1   2   3
2   4   5
3   6   7
4   8   9

In [10]:
for i in np.arange(df.shape[0]):
    for j in np.arange(df.shape[1]):
        print(df.iloc[i,j])

0
1
2
3
4
5
6
7
8
9


In [11]:
df.columns=['x','y']
df

x  y
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [12]:
b0 = 1
b1 = 1
for i in np.arange(df.shape[0]):
    print(df.x[i], b0 + b1 * df.x[i], df.y[i] -  b0 + b1 * df.x[i] )

0 1 0
2 3 4
4 5 8
6 7 12
8 9 16


# detect and clean missing values

In [13]:
# check if there is any missing values
arr = np.array([1,2,np.nan,4])
arr

array([ 1.,  2., nan,  4.])

In [14]:
np.isnan(arr)

array([False, False,  True, False])

In [15]:
ser = pd.Series(arr)
ser.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [16]:
# opposite, check if array elements are not nan
~np.isnan(arr)

array([ True,  True, False,  True])

In [17]:
# same for Series
ser.notna()

0     True
1     True
2    False
3     True
dtype: bool

In [18]:
# df with nan values

In [19]:
x1 = np.array([1,2,np.nan,4])
x2 = np.array([1,np.nan,np.nan,4])
df = pd.DataFrame({'x1':x1,'x2':x2})
df

x1   x2
0  1.0  1.0
1  2.0  NaN
2  NaN  NaN
3  4.0  4.0

In [20]:
df.x1.isna().sum()

1

In [21]:
df.isna().sum()

x1    1
x2    2
dtype: int64

In [22]:
# drop columns which have any nan values
df.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [23]:
# drop rows or indexes which have nan values
df.dropna(axis='index')

x1   x2
0  1.0  1.0
3  4.0  4.0

In [24]:
# treatment of missing values
# use a specific value, like zero or some other
df.fillna(0)

x1   x2
0  1.0  1.0
1  2.0  0.0
2  0.0  0.0
3  4.0  4.0

In [25]:
# column wise default values
df.fillna({'x1': 0.5, 'x2': 0.75})

x1    x2
0  1.0  1.00
1  2.0  0.75
2  0.5  0.75
3  4.0  4.00

In [26]:
df

x1   x2
0  1.0  1.0
1  2.0  NaN
2  NaN  NaN
3  4.0  4.0

In [27]:
# forward fill, fill nan with the previous value
df.fillna(method="ffill")

x1   x2
0  1.0  1.0
1  2.0  1.0
2  2.0  1.0
3  4.0  4.0

In [28]:
# forward fill, fill nan with the next value
df.fillna(method="bfill")

x1   x2
0  1.0  1.0
1  2.0  4.0
2  4.0  4.0
3  4.0  4.0

In [29]:
df.fillna(df.mean())

x1   x2
0  1.000000  1.0
1  2.000000  2.5
2  2.333333  2.5
3  4.000000  4.0

# transformation

In [30]:
# replace (find some value and replace with a supplied value)

In [31]:
x1 = pd.Series([-4, -5, 24, -4, 10])
x2 = pd.Series([24, 14, 15,  7,  4])

In [32]:
df = pd.concat([x1,x2],axis=1)
df.columns=['x1','x2']

In [33]:
df.replace([-4,-5],np.nan)

x1    x2
0   NaN  24.0
1   NaN  14.0
2  24.0  15.0
3   NaN   7.0
4  10.0   4.0

In [34]:
x1 = pd.Series(['M','F','M','F','F'])
x2 = pd.Series([24, 14, 15,  7,  4])
df = pd.concat([x1,x2],axis=1)
df.columns=['x1','x2']
df

x1  x2
0  M  24
1  F  14
2  M  15
3  F   7
4  F   4

In [35]:
mapper_dict = {'F':0,'M':1}

In [36]:
# map function usually takes a function and an iterable.
# there is another feature of map where it takes a iterable as keys and fetches values from a dict object.
# this is useful to encode columns
df['x1'].map(mapper_dict)

0    1
1    0
2    1
3    0
4    0
Name: x1, dtype: int64

In [37]:
df['x1_encoded'] = df['x1'].map(mapper_dict)
df

x1  x2  x1_encoded
0  M  24           1
1  F  14           0
2  M  15           1
3  F   7           0
4  F   4           0

In [38]:
decode_dict = {0:'M',1:'F'}
df['x1_encoded'].map(decode_dict)

0    F
1    M
2    F
3    M
4    M
Name: x1_encoded, dtype: object

In [39]:
ser = pd.Series(np.arange(50))

In [40]:
df = pd.DataFrame(ser)
df.columns=['x1']
df.head()

x1
0   0
1   1
2   2
3   3
4   4

In [41]:
# cut x1 into four parts and assign the given labels
df['lbl']=pd.cut(df.x1,4,labels=[1,2,3,4])

In [42]:
df.head()

x1 lbl
0   0   1
1   1   1
2   2   1
3   3   1
4   4   1

In [43]:
df.lbl.value_counts()

1    13
4    13
2    12
3    12
Name: lbl, dtype: int64

In [44]:
marks = np.random.randint(low=0,high=100,size=5)

In [89]:
marks

[64, 67, 79, 82]

In [88]:
print(marks)
grades = pd.cut(marks, bins=[0,40,60,75,100], include_lowest=True, labels=['Fail','Pass','First','Distinction'],right=True)
print(grades)

[64, 67, 79, 82]
['First', 'First', 'Distinction', 'Distinction']
Categories (4, object): ['Fail' < 'Pass' < 'First' < 'Distinction']


In [46]:
grades

['Fail', 'Fail', 'First', 'Distinction', 'Pass']
Categories (4, object): ['Fail' < 'Pass' < 'First' < 'Distinction']

In [47]:
pd.qcut(ser,2)

0     (-0.001, 24.5]
1     (-0.001, 24.5]
2     (-0.001, 24.5]
3     (-0.001, 24.5]
4     (-0.001, 24.5]
5     (-0.001, 24.5]
6     (-0.001, 24.5]
7     (-0.001, 24.5]
8     (-0.001, 24.5]
9     (-0.001, 24.5]
10    (-0.001, 24.5]
11    (-0.001, 24.5]
12    (-0.001, 24.5]
13    (-0.001, 24.5]
14    (-0.001, 24.5]
15    (-0.001, 24.5]
16    (-0.001, 24.5]
17    (-0.001, 24.5]
18    (-0.001, 24.5]
19    (-0.001, 24.5]
20    (-0.001, 24.5]
21    (-0.001, 24.5]
22    (-0.001, 24.5]
23    (-0.001, 24.5]
24    (-0.001, 24.5]
25      (24.5, 49.0]
26      (24.5, 49.0]
27      (24.5, 49.0]
28      (24.5, 49.0]
29      (24.5, 49.0]
30      (24.5, 49.0]
31      (24.5, 49.0]
32      (24.5, 49.0]
33      (24.5, 49.0]
34      (24.5, 49.0]
35      (24.5, 49.0]
36      (24.5, 49.0]
37      (24.5, 49.0]
38      (24.5, 49.0]
39      (24.5, 49.0]
40      (24.5, 49.0]
41      (24.5, 49.0]
42      (24.5, 49.0]
43      (24.5, 49.0]
44      (24.5, 49.0]
45      (24.5, 49.0]
46      (24.5, 49.0]
47      (24.5

In [48]:
# supply quantiles to cut at
df['qcuts']=pd.qcut(ser, [0,0.25, 0.5, 0.75,1.0],labels=['preQ1','Q1Q2','Q2Q3','postQ3'])
df.head()

x1 lbl  qcuts
0   0   1  preQ1
1   1   1  preQ1
2   2   1  preQ1
3   3   1  preQ1
4   4   1  preQ1

# • Combining and merging data sets,

In [49]:
# pd merge: 
# inner join combines common rows from multiple dataframes

roll_1 = [1,2,3,4]
marks_1 = [56,87,49,98]
df_1 = pd.DataFrame({'roll_1':roll_1, 'marks_1':marks_1})
roll_2 = [1,1,3,5]
marks_2 = [64,67,79,82]
df_2 = pd.DataFrame({'roll_2':roll_2, 'marks_2':marks_2})
print(df_1)
print(df_2)

   roll_1  marks_1
0       1       56
1       2       87
2       3       49
3       4       98
   roll_2  marks_2
0       1       64
1       1       67
2       3       79
3       5       82


In [50]:
pd.merge(df_1,df_2,left_on=['roll_1'],right_on=['roll_2'])

roll_1  marks_1  roll_2  marks_2
0       1       56       1       64
1       1       56       1       67
2       3       49       3       79

In [51]:
# match indexes of both dataframes
pd.merge(df_1,df_2,left_index=True,right_index=True)

roll_1  marks_1  roll_2  marks_2
0       1       56       1       64
1       2       87       1       67
2       3       49       3       79
3       4       98       5       82

# in the above statements, there was a default parameters how=inner

In [52]:
roll = [1,2,3,4]
marks_1 = [56,87,49,98]
df_1 = pd.DataFrame({'roll':roll, 'marks_1':marks_1})
roll = [1,1,3,5]
marks_2 = [64,67,79,82]
df_2 = pd.DataFrame({'roll':roll, 'marks_2':marks_2})
print(df_1)
print(df_2)

   roll  marks_1
0     1       56
1     2       87
2     3       49
3     4       98
   roll  marks_2
0     1       64
1     1       67
2     3       79
3     5       82


In [53]:
# considering the common column and only returning the rows for which values match
pd.merge(df_1,df_2,how='inner')

roll  marks_1  marks_2
0     1       56       64
1     1       56       67
2     3       49       79

In [54]:
# consider all the left rows, union columns of the right df and any available values. Fill rest with nan. any matching values
pd.merge(df_1,df_2,on=['roll'],how='left')

roll  marks_1  marks_2
0     1       56     64.0
1     1       56     67.0
2     2       87      NaN
3     3       49     79.0
4     4       98      NaN

In [55]:
# consider union of all columns, fill values available from both df, rest of the cells get nan
pd.merge(df_1,df_2,on=['roll'],how='outer')

roll  marks_1  marks_2
0     1     56.0     64.0
1     1     56.0     67.0
2     2     87.0      NaN
3     3     49.0     79.0
4     4     98.0      NaN
5     5      NaN     82.0

In [56]:
# consider all the right df rows, union columns of the left df and any available values. Fill rest with nan. any matching values
pd.merge(df_1,df_2,on=['roll'],how='right')

roll  marks_1  marks_2
0     1     56.0       64
1     1     56.0       67
2     3     49.0       79
3     5      NaN       82

In [57]:
# side by side
pd.concat([df_1,df_2], axis=1,join='inner')

roll  marks_1  roll  marks_2
0     1       56     1       64
1     2       87     1       67
2     3       49     3       79
3     4       98     5       82

# pd concat

In [58]:
x1 = pd.Series([1,2,3,4])
x2 = pd.Series([7,2,7,1])
x3 = pd.Series([-1,0.2,3,4])

In [59]:
pd.concat([x1,x2,x3], axis='index')

0    1.0
1    2.0
2    3.0
3    4.0
0    7.0
1    2.0
2    7.0
3    1.0
0   -1.0
1    0.2
2    3.0
3    4.0
dtype: float64

In [60]:
pd.concat([x1,x2,x3],axis='columns')

0  1    2
0  1  7 -1.0
1  2  2  0.2
2  3  7  3.0
3  4  1  4.0

In [61]:
# stack on top
pd.concat([df_1,df_2], axis=0)

roll  marks_1  marks_2
0     1     56.0      NaN
1     2     87.0      NaN
2     3     49.0      NaN
3     4     98.0      NaN
0     1      NaN     64.0
1     1      NaN     67.0
2     3      NaN     79.0
3     5      NaN     82.0

In [62]:
roll = [1,2,3,4]
marks = [56,87,49,98]
df_1 = pd.DataFrame({'roll':roll, 'marks':marks})
roll = [5,6,7,8]
marks = [64,67,79,82]
df_2 = pd.DataFrame({'roll':roll, 'marks':marks})
print(df_1)
print(df_2)

   roll  marks
0     1     56
1     2     87
2     3     49
3     4     98
   roll  marks
0     5     64
1     6     67
2     7     79
3     8     82


In [63]:
pd.concat([df_1,df_2])

roll  marks
0     1     56
1     2     87
2     3     49
3     4     98
0     5     64
1     6     67
2     7     79
3     8     82

In [64]:
pd.concat([df_1,df_2]).reset_index()

index  roll  marks
0      0     1     56
1      1     2     87
2      2     3     49
3      3     4     98
4      0     5     64
5      1     6     67
6      2     7     79
7      3     8     82

In [65]:
pd.concat([df_1,df_2],axis='columns')

roll  marks  roll  marks
0     1     56     5     64
1     2     87     6     67
2     3     49     7     79
3     4     98     8     82

# pivoting

In [66]:
df = pd.read_excel('sales.xlsx',sheet_name="Sheet1")
df

region product  sales
0        urban       a      1
1        urban       b      2
2        urban       c      3
3        urban       d      4
4        rural       a      5
5        rural       b      6
6        rural       c      7
7        rural       d      8
8   semi-urban       a      9
9   semi-urban       b     10
10  semi-urban       c     11
11  semi-urban       d     12

In [67]:
df.set_index(['region','product'],inplace=True)

In [68]:
df.index

MultiIndex([(     'urban', 'a'),
            (     'urban', 'b'),
            (     'urban', 'c'),
            (     'urban', 'd'),
            (     'rural', 'a'),
            (     'rural', 'b'),
            (     'rural', 'c'),
            (     'rural', 'd'),
            ('semi-urban', 'a'),
            ('semi-urban', 'b'),
            ('semi-urban', 'c'),
            ('semi-urban', 'd')],
           names=['region', 'product'])

In [69]:
# switch index order
df.swaplevel("product","region")

sales
product region           
a       urban           1
b       urban           2
c       urban           3
d       urban           4
a       rural           5
b       rural           6
c       rural           7
d       rural           8
a       semi-urban      9
b       semi-urban     10
c       semi-urban     11
d       semi-urban     12

In [70]:
# use .xs (cross-section) to query from multilevel indexed df
df.xs('urban',level='region')

sales
product       
a            1
b            2
c            3
d            4

In [71]:
df.xs('a',level='product')

sales
region           
urban           1
rural           5
semi-urban      9

In [72]:
# cross tabulated
# this requires one value for each combination of region + product
# heads up: groupby operation can produce this if there are multiple rows for region + product combo
df.unstack()

sales            
product        a   b   c   d
region                      
rural          5   6   7   8
semi-urban     9  10  11  12
urban          1   2   3   4

In [73]:
df.unstack().stack()

sales
region     product       
rural      a            5
           b            6
           c            7
           d            8
semi-urban a            9
           b           10
           c           11
           d           12
urban      a            1
           b            2
           c            3
           d            4

In [74]:
df.unstack(level=0)

sales                 
region  rural semi-urban urban
product                       
a           5          9     1
b           6         10     2
c           7         11     3
d           8         12     4

In [75]:
df.unstack(level=1)

sales            
product        a   b   c   d
region                      
rural          5   6   7   8
semi-urban     9  10  11  12
urban          1   2   3   4

In [76]:
df.unstack()

sales            
product        a   b   c   d
region                      
rural          5   6   7   8
semi-urban     9  10  11  12
urban          1   2   3   4

In [77]:
df.head()

sales
region product       
urban  a            1
       b            2
       c            3
       d            4
rural  a            5

In [78]:
# reset_index() makes region and product as columns in the df and then passes to pivot
# pivot() expects unique combinations of index + columns, here region + product
df.reset_index().pivot(index='region', columns='product', values='sales')

product     a   b   c   d
region                   
rural       5   6   7   8
semi-urban  9  10  11  12
urban       1   2   3   4

In [79]:
# notice the last row. it is a duplicate combination of region and product
df = pd.read_excel('sales.xlsx',sheet_name="Sheet2")
df

region product  sales
0        urban       a      1
1        urban       b      2
2        urban       c      3
3        urban       d      4
4        rural       a      5
5        rural       b      6
6        rural       c      7
7        rural       d      8
8   semi-urban       a      9
9   semi-urban       b     10
10  semi-urban       c     11
11  semi-urban       d     12
12       urban       a      1

In [80]:
# df.reset_index().pivot() this will not work as there are duplicate rows with region+product combinations
# pivot_table() has aggregating function and can be used

In [81]:
df.pivot_table(index='region', columns='product', values='sales',aggfunc=np.sum)

product     a   b   c   d
region                   
rural       5   6   7   8
semi-urban  9  10  11  12
urban       2   2   3   4

In [82]:
df_pivot_tab = df.pivot_table(index='region', columns='product', values='sales',aggfunc=np.sum)

In [83]:
df_pivot_tab

product     a   b   c   d
region                   
rural       5   6   7   8
semi-urban  9  10  11  12
urban       2   2   3   4

In [84]:
df_pivot_tab.index

Index(['rural', 'semi-urban', 'urban'], dtype='object', name='region')

In [85]:
df_pivot_tab.reset_index()

product      region  a   b   c   d
0             rural  5   6   7   8
1        semi-urban  9  10  11  12
2             urban  2   2   3   4

In [86]:
df_pivot_tab.reset_index(inplace=True)

In [87]:
# melt unpivots
df_pivot_tab.melt(id_vars='region',value_vars=['a','b','c','d'])

region product  value
0        rural       a      5
1   semi-urban       a      9
2        urban       a      2
3        rural       b      6
4   semi-urban       b     10
5        urban       b      2
6        rural       c      7
7   semi-urban       c     11
8        urban       c      3
9        rural       d      8
10  semi-urban       d     12
11       urban       d      4